# Generated by Django 4.0.10 on 2023-03-12 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_personaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='id',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='pd_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
