# Generated by Django 4.0.10 on 2023-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_customotp_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customotp',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customotp',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
