# Generated by Django 4.0.10 on 2023-03-23 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customotp_counter_customotp_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created  at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customotp',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='latsmodified_at'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created  at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='lastmodified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='latsmodified_at'),
        ),
    ]
